In [14]:
#QUESTION 4
import numpy as np

# Define matrices and vectors
X = np.array([[1, 7], [-8, 6], [3, 1]])
Y = np.array([[0, 4, 6, -8], [1, -3, 5, 7], [11, 13, 9, 9], [-1, 0, 8, 7]])
Z = np.array([[0, 4, 8, 1], [-3, 5, 17, 11]])
A = np.array([[1, 17], [2, 14]])
b = np.array([19, -11, 13])
c = np.array([12, -11, 10])
x = np.array([1, 2, 3])
y = np.array([3, 3, 1])

# Calculations
result_1 = np.outer(x, y @ x)
print("1. xyy^T x^T:\n", result_1)

result_2 = 3 * c - 9
print("\n2. 3c - 9:\n", result_2)

trace_A = np.trace(A.T @ A)
result_3 = trace_A * A
print("\n3. ⟨A, A⟩ · A:\n", result_3)

result_4 = 2 * (X @ Z)
print("\n4. 2XZ:\n", result_4)

result_5 = (b @ c) * A
print("\n5. (bc)A:\n", result_5)

result_6 = (b @ X) @ A
print("\n6. bXA:\n", result_6)

result_7 = c * x
print("\n7. c ⊙ x:\n", result_7)

result_8 = b * y
print("\n8. b ⊙ y:\n", result_8)

result_9 = np.outer(c, x)
print("\n9. c ⊗ x:\n", result_9)

result_10 = Y @ Z.T
print("\n10. Y Z^T:\n", result_10)



1. xyy^T x^T:
 [[12]
 [24]
 [36]]

2. 3c - 9:
 [ 27 -42  21]

3. ⟨A, A⟩ · A:
 [[ 490 8330]
 [ 980 6860]]

4. 2XZ:
 [[-42  78 254 156]
 [-36  -4  76 116]
 [ -6  34  82  28]]

5. (bc)A:
 [[ 479 8143]
 [ 958 6706]]

6. bXA:
 [ 306 3602]

7. c ⊙ x:
 [ 12 -22  30]

8. b ⊙ y:
 [ 57 -33  13]

9. c ⊗ x:
 [[ 12  24  36]
 [-11 -22 -33]
 [ 10  20  30]]

10. Y Z^T:
 [[ 56  34]
 [ 35 144]
 [133 284]
 [ 71 216]]


In [15]:
#QUESTION 5
import numpy as np

# Create matrices and vectors
X = np.array([[2, 3], [9, 1]])
Y = np.array([[1, 0], [2, 1]])
x = np.array([1, 3])
y = np.array([2, 4])

# Extract and print values
print("1st column of X:\n", X[:, 0])

print("\n2nd row of Y:\n", Y[1, :])

print("\nBottom right value of X:\n", X[-1, -1])

# Matrix addition and operations
print("\nX + Y:\n", X + Y)

YX = Y @ X
print("\nX + YX:\n", X + YX)

# Hadamard product
print("\nHadamard product x ⊙ y:\n", x * y)

# Outer product
print("\nOuter product x ⊗ y:\n", np.outer(x, y))

# Dot product
print("\nDot product XY:\n", X @ Y)

# Inner product (sum of element-wise products)
print("\nInner product ⟨X, Y⟩:\n", np.sum(X * Y))



1st column of X:
 [2 9]

2nd row of Y:
 [2 1]

Bottom right value of X:
 1

X + Y:
 [[ 3  3]
 [11  2]]

X + YX:
 [[ 4  6]
 [22  8]]

Hadamard product x ⊙ y:
 [ 2 12]

Outer product x ⊗ y:
 [[ 2  4]
 [ 6 12]]

Dot product XY:
 [[ 8  3]
 [11  1]]

Inner product ⟨X, Y⟩:
 21


In [16]:
#QUESTION 7
import numpy as np

data_matrix = np.loadtxt('hw1.csv', delimiter=',')

print("Data Matrix:")
print(data_matrix)

Data Matrix:
[[1. 2. 1.]
 [2. 0. 0.]
 [2. 1. 1.]
 [1. 2. 5.]]
