In [6]:
import numpy as np
from numpy import array
from numpy import trace

x = array([[2],[6]])
y = array([[1],[0]])
X = array([[7,5],[3,6]])
Y = array([[2,4],[1,0]])
Z = array([[4,-1,0],[1,1,1]])

# 1 Tr(xx^T) + <x,y>
result_1 = np.trace(np.dot(x, x.T)) + np.dot(x.T, y)

# 2 x ⊗ y
result_2 = np.kron(x, y)

# 3 Y ⊙ X
result_3 = np.multiply(Y, X)

# 4 2X + 2Y + X^TY
result_4 = 2*X + 2*Y + np.dot(X.T, Y)

# 5 <Y,Y>
result_5 = np.dot(Y.T, Y)

# 6 ZZ^Tx
result_6 = np.dot(np.dot(Z, Z.T), x)

print(result_1)
print(------)
print(result_2)
print(result_3)
print(result_4)
print(result_5)
print(result_6)

[[42]]
[[2]
 [0]
 [6]
 [0]]
[[14 20]
 [ 3  0]]
[[35 46]
 [24 32]]
[[ 5  8]
 [ 8 16]]
[[52]
 [24]]
