In [10]:
#Load A,B,C,x,y,z from file into arrays
import numpy as np
from numpy import genfromtxt


A = genfromtxt('/Users/shreyas/Desktop/ML/test_A.csv', delimiter=',')
B = genfromtxt('/Users/shreyas/Desktop/ML/test_B.csv', delimiter=',')
C = genfromtxt('/Users/shreyas/Desktop/ML/test_C.csv', delimiter=',')
x = genfromtxt('/Users/shreyas/Desktop/ML/test_x.csv', delimiter=',')
y = genfromtxt('/Users/shreyas/Desktop/ML/test_y.csv', delimiter=',')
z = genfromtxt('/Users/shreyas/Desktop/ML/test_z.csv', delimiter=',')


x = x.reshape(5,1)
y = y.reshape(5,1)
z = z.reshape(3,1)

#1 <A,A>
A_dot_A = np.dot(A.T,A)


#2 A hadddamard B
A_hadamard_B = np.multiply(A,B)

#3 Tr(x ⨂ y )
x_kron_y = np.kron(x,y)

#4 AB^T
AB_T = np.dot(A,B.T)

#5 A^TBCx
ATBCx = A.dot(B.T).dot(C).dot(x)

#6 C(x + y)
C_x_plus_y = np.dot(C,x+y)

#7 ||x||0, ||x||1, ||x||2, ||x||inf
x_0 = np.count_nonzero(x)
x_1 = np.linalg.norm(x,1)
x_2 = np.linalg.norm(x,2)
x_inf = np.linalg.norm(x,np.inf)

#8 ||y||0, ||y||1, ||y||2, ||y||inf
y_0 = np.count_nonzero(y)
y_1 = np.linalg.norm(y,1)
y_2 = np.linalg.norm(y,2)
y_inf = np.linalg.norm(y,np.inf)

#9 ||z||0, ||z||1, ||z||2, ||z||inf
z_0 = np.count_nonzero(z)
z_1 = np.linalg.norm(z,1)
z_2 = np.linalg.norm(z,2)
z_inf = np.linalg.norm(z,np.inf)

print("A_dot_A = ", A_dot_A)
print("A_hadamard_B = ", A_hadamard_B)
print("x_kron_y = ", x_kron_y)
print("AB_T = ", AB_T)
print("ATBCx = ", ATBCx)
print("C_x_plus_y = ", C_x_plus_y)
print("x_0 = ", x_0)
print("x_1 = ", x_1)
print("x_2 = ", x_2)
print("x_inf = ", x_inf)
print("y_0 = ", y_0)
print("y_1 = ", y_1)
print("y_2 = ", y_2)
print("y_inf = ", y_inf)
print("z_0 = ", z_0)
print("z_1 = ", z_1)
print("z_2 = ", z_2)
print("z_inf = ", z_inf)





A_dot_A =  [[ 6.  4.  2.]
 [ 4. 10.  8.]
 [ 2.  8.  9.]]
A_hadamard_B =  [[0. 2. 2.]
 [2. 2. 0.]
 [2. 4. 0.]
 [2. 0. 0.]
 [0. 4. 1.]
 [0. 0. 0.]]
x_kron_y =  [[0.]
 [0.]
 [2.]
 [1.]
 [2.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [4.]
 [2.]
 [4.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
AB_T =  [[4. 6. 2. 2. 4. 3.]
 [2. 4. 6. 6. 2. 1.]
 [6. 9. 6. 6. 6. 4.]
 [0. 1. 2. 2. 0. 0.]
 [5. 6. 4. 4. 5. 3.]
 [0. 0. 0. 0. 0. 0.]]
ATBCx =  [[ 62.]
 [ 82.]
 [122.]
 [ 22.]
 [ 88.]
 [  0.]]
C_x_plus_y =  [[ 7.]
 [ 8.]
 [14.]
 [ 9.]
 [ 7.]
 [ 9.]]
x_0 =  2
x_1 =  3.0
x_2 =  2.23606797749979
x_inf =  2.0
y_0 =  3
y_1 =  5.0
y_2 =  3.0
y_inf =  2.0
z_0 =  2
z_1 =  3.0
z_2 =  2.23606797749979
z_inf =  2.0
